version: '3'

services:
  traefik:
    image: traefik:v1.7.4
    command: --docker --docker.domain=dominio.com.br
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerdata/traefik/traefik.toml:/traefik.toml
      - /dockerdata/traefik/certs/:/etc/traefik/certs/
    labels:
      - "traefik.frontend.rule=Host:dominio.com.br"
      - "traefik.port=8080"
    container_name: traefik
    restart: always

networks:
  proxy:
    external: true